# Copyright 2018, alex at staticlibs.net
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

image: Visual Studio 2013

clone_folder: c:\projects\wilton

build: off

environment:
  matrix:
    - WILTON_WIN_ARCH: _x86
    - WILTON_WIN_ARCH: ""

matrix:
  fast_finish: true

install:
#  - cd ..
#  - git clone https://github.com/wilton-iot/wilton
#  - cd wilton
  - cmd /c resources\ci\appveyor-checkout.bat

build_script:
  - echo "PR support is enabled for root repo"
  - cmd /c resources\ci\appveyor%WILTON_WIN_ARCH%.bat
  - robocopy build c:/projects/wilton/ wilton_%APPVEYOR_REPO_TAG_NAME%%WILTON_WIN_ARCH%.msi /ndl /njh /njs /nc /ns /np || true

artifacts:
  - path: wilton_%APPVEYOR_REPO_TAG_NAME%%WILTON_WIN_ARCH%.msi
    name: wilton_%APPVEYOR_REPO_TAG_NAME%%WILTON_WIN_ARCH%.msi

deploy:
  description: "%APPVEYOR_REPO_TAG_NAME%"
  provider: GitHub
  auth_token:
    secure: VShPexae/Ct8Y4Rn0YvHmiX/Sih1Xs+qGHfU2JEmuAuXVb/KVsc8B72MlG7TCw0e
  artifact: wilton_%APPVEYOR_REPO_TAG_NAME%%WILTON_WIN_ARCH%.msi
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true 
